[tox]
requires =
  tox>=4
  tox-uv
envlist =
  py314{,t}-{latest,min}
  typecheck
skip_missing_interpreters = true

[gh-actions]
python =
  3.14: py314
  3.14t: py314t

[gh-actions:env]
DEPENDS =
  latest: latest
  min: min

[testenv]
description = Pytest with coverage
runner =
  latest: uv-venv-lock-runner
  !latest: uv-venv-runner
pass_env =
  # Pass user color preferences through
  PY_COLORS
  FORCE_COLOR
  NO_COLOR
  CLICOLOR
  CLICOLOR_FORCE
package = editable
set_env =
  py3{13-15}t: PYTHONGIL={env:PYTHONGIL:0}
dependency_groups = test
uv_resolution =
  min: lowest-direct

commands =
  pytest --doctest-modules -svv \
    --cov src --cov tests --cov-report xml:cov.xml \
    {posargs}

[testenv:typecheck]
description = Check type consistency
runner = uv-venv-lock-runner
dependency_groups =
  test
  types
commands =
  mypy src tests
